

title: ZouchengHong's Portfolio
email: zoucheng_hong@126.com
description: >- 
  Hope to be a good researcher ~ 
  Nice to meet you here ~~
  Feel free to contact with me ~~~
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zouchenghong.github.io"
github_username:  ZouchengHong

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
